//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace GlobalSchoolSearch2017_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "School")]
        public string SchoolName { get; set; }
        [Required]
        [Display(Name = "City")]
        public string CityName { get; set; }
        [Required]
        [Display(Name = "Country")]
        public string CountryName { get; set; }
        [Required]
        [Display(Name = "Review Comments")]
        public string ReviewText { get; set; }
        [Required]
        [Range(minimum:1, maximum:5)]
        public double Rating { get; set; }

        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual School School { get; set; }
    }
}
